name: reactive_component
description: A package that supports for creating stream-based reactive components.
version: 0.3.0-nullsafety.0
homepage: https://github.com/polyflection/reactive_component

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.6
  pedantic: ^1.10.0-nullsafety.3

dev_dependencies:
  test: ^1.16.0-nullsafety.11
