name: reactive_component
description: Reactive Component.
version: 0.1.1
homepage: https://github.com/polyflection/reactive_component

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  meta: ^1.0.0
  pedantic: ^1.9.0

dev_dependencies:
  test:
