name: flutter_counter
description: A Flutter counter example of package:reactive_component.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_component:
    path: ../../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
